/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ManageProducts extends javax.swing.JFrame {

    /**
     * Creates new form CompanySettings
     */
    public ManageProducts() {
        initComponents();
        autoId();
        FillCombo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPaneIngredient = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jButtonReset2 = new javax.swing.JButton();
        jTextFieldIngreNumber5 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTextFieldIngreNumber7 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldIngreNumber8 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jButtonAddProduct = new javax.swing.JButton();
        jButtonEditProduct = new javax.swing.JButton();
        jButtonDeleteProduct = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButtonPrintProduct = new javax.swing.JButton();
        jButtonViewProduct = new javax.swing.JButton();
        jButtonProductSearch = new javax.swing.JButton();
        jButtonViewProductPriceList = new javax.swing.JButton();
        jButtonPrintProductPriceList = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jTextFieldIngDiscription = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextFieldIngName = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextFieldIngreNumber = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jComboBoxName = new javax.swing.JComboBox();
        jPanel14 = new javax.swing.JPanel();
        jButtonAddIngre = new javax.swing.JButton();
        jButtonEditIngre = new javax.swing.JButton();
        jButtonDeleteIngre = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButtonPrintIngre = new javax.swing.JButton();
        jButtonViewIngre = new javax.swing.JButton();
        jButtonIngreSearch = new javax.swing.JButton();
        jButtonViewIngreList = new javax.swing.JButton();
        jButtonPrintIngreList = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1380, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(1380, 780));
        jPanel4.setName(""); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clogo.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 226, 226));
        jLabel2.setText("Keisuke Bakers ");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Manage");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Products & Ingredients");

        jTabbedPaneIngredient.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPaneIngredient.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Manage Products Informations");

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product name", "Main category", "Weight", "Date"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel51.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel51.setText("Product Name");

        jButtonReset2.setBackground(new java.awt.Color(204, 204, 204));
        jButtonReset2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonReset2.setText("Reset");
        jButtonReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReset2jButtonResetActionPerformed(evt);
            }
        });

        jTextFieldIngreNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngreNumber5jTextFieldIngreNumberActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel52.setText("Main Category");

        jTextFieldIngreNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngreNumber7jTextFieldIngreNumberActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel53.setText("Weight");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel54.setText("Price");

        jTextFieldIngreNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngreNumber8jTextFieldIngreNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                            .addComponent(jTextFieldIngreNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonReset2))
                        .addComponent(jTextFieldIngreNumber7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                            .addComponent(jLabel51)
                            .addGap(712, 712, 712))
                        .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldIngreNumber5, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel51)
                .addGap(11, 11, 11)
                .addComponent(jTextFieldIngreNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53)
                .addGap(14, 14, 14)
                .addComponent(jTextFieldIngreNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel54)
                .addGap(12, 12, 12)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIngreNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset2))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4))
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddProduct.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonAddProduct.setForeground(new java.awt.Color(0, 102, 153));
        jButtonAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-30.png"))); // NOI18N
        jButtonAddProduct.setText("Add Product");
        jButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductActionPerformed(evt);
            }
        });

        jButtonEditProduct.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditProduct.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEditProduct.setForeground(new java.awt.Color(0, 102, 153));
        jButtonEditProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-property-30.png"))); // NOI18N
        jButtonEditProduct.setText("Edit Product");
        jButtonEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditProductActionPerformed(evt);
            }
        });

        jButtonDeleteProduct.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeleteProduct.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonDeleteProduct.setForeground(new java.awt.Color(0, 102, 153));
        jButtonDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-view-30.png"))); // NOI18N
        jButtonDeleteProduct.setText("Delete Product");
        jButtonDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteProductActionPerformed(evt);
            }
        });

        jButtonPrintProduct.setBackground(new java.awt.Color(0, 0, 51));
        jButtonPrintProduct.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPrintProduct.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrintProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-print-30.png"))); // NOI18N
        jButtonPrintProduct.setText("Print Products");

        jButtonViewProduct.setBackground(new java.awt.Color(0, 0, 51));
        jButtonViewProduct.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonViewProduct.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-view-30.png"))); // NOI18N
        jButtonViewProduct.setText("View Products");

        jButtonProductSearch.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProductSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonProductSearch.setForeground(new java.awt.Color(0, 102, 153));
        jButtonProductSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-bar-30.png"))); // NOI18N
        jButtonProductSearch.setText("Search");

        jButtonViewProductPriceList.setBackground(new java.awt.Color(0, 0, 51));
        jButtonViewProductPriceList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonViewProductPriceList.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewProductPriceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-view-30.png"))); // NOI18N
        jButtonViewProductPriceList.setText("View Products Price List");

        jButtonPrintProductPriceList.setBackground(new java.awt.Color(0, 0, 51));
        jButtonPrintProductPriceList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPrintProductPriceList.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrintProductPriceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-print-30.png"))); // NOI18N
        jButtonPrintProductPriceList.setText("Print Products Price List");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonProductSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonViewProductPriceList)
                            .addComponent(jButtonPrintProductPriceList)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEditProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jButtonViewProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPrintProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProductSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonViewProductPriceList)
                .addGap(18, 18, 18)
                .addComponent(jButtonPrintProductPriceList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonAddProduct)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditProduct)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeleteProduct)
                .addGap(18, 18, 18)
                .addComponent(jButtonViewProduct)
                .addGap(18, 18, 18)
                .addComponent(jButtonPrintProduct)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneIngredient.addTab("Products", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Manage Ingredients Informations");

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingredient name", "Price for 1", "Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel47.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel47.setText("Ingredient Name");

        jButtonReset.setBackground(new java.awt.Color(204, 204, 204));
        jButtonReset.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTextFieldIngDiscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngDiscriptionjTextFieldIngreNumberActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel48.setText("Discription");

        jTextFieldIngName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngNamejTextFieldIngreNumberActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel49.setText("Ingredient Number");

        jTextFieldIngreNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngreNumberjTextFieldIngreNumberActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel55.setText("Available Ingredient Name");

        jComboBoxName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel49)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIngreNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldIngName)
                    .addComponent(jButtonReset)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(712, 712, 712))
                    .addComponent(jLabel48, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIngDiscription, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(jTextFieldIngreNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(jComboBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIngName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldIngDiscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonReset)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonAddIngre.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddIngre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonAddIngre.setForeground(new java.awt.Color(0, 102, 153));
        jButtonAddIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-30.png"))); // NOI18N
        jButtonAddIngre.setText("Add Ingredient");
        jButtonAddIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddIngreActionPerformed(evt);
            }
        });

        jButtonEditIngre.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditIngre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEditIngre.setForeground(new java.awt.Color(0, 102, 153));
        jButtonEditIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-property-30.png"))); // NOI18N
        jButtonEditIngre.setText(" Update Ingredient");
        jButtonEditIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditIngreActionPerformed(evt);
            }
        });

        jButtonDeleteIngre.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeleteIngre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonDeleteIngre.setForeground(new java.awt.Color(0, 102, 153));
        jButtonDeleteIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-view-30.png"))); // NOI18N
        jButtonDeleteIngre.setText("Delete Ingredient");
        jButtonDeleteIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteIngreActionPerformed(evt);
            }
        });

        jButtonPrintIngre.setBackground(new java.awt.Color(0, 0, 51));
        jButtonPrintIngre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPrintIngre.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrintIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-print-30.png"))); // NOI18N
        jButtonPrintIngre.setText("Print Ingredients");

        jButtonViewIngre.setBackground(new java.awt.Color(0, 0, 51));
        jButtonViewIngre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonViewIngre.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewIngre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-view-30.png"))); // NOI18N
        jButtonViewIngre.setText("View Ingredients");

        jButtonIngreSearch.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIngreSearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonIngreSearch.setForeground(new java.awt.Color(0, 102, 153));
        jButtonIngreSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-search-bar-30.png"))); // NOI18N
        jButtonIngreSearch.setText("Search");
        jButtonIngreSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngreSearchActionPerformed(evt);
            }
        });

        jButtonViewIngreList.setBackground(new java.awt.Color(0, 0, 51));
        jButtonViewIngreList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonViewIngreList.setForeground(new java.awt.Color(255, 255, 255));
        jButtonViewIngreList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-view-30.png"))); // NOI18N
        jButtonViewIngreList.setText("View Ingredients Price List");

        jButtonPrintIngreList.setBackground(new java.awt.Color(0, 0, 51));
        jButtonPrintIngreList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPrintIngreList.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPrintIngreList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-print-30.png"))); // NOI18N
        jButtonPrintIngreList.setText("Print Ingredients Price List");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIngreSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonViewIngreList)
                            .addComponent(jButtonPrintIngreList)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonEditIngre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddIngre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteIngre, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jButtonViewIngre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPrintIngre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIngreSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonViewIngreList)
                .addGap(18, 18, 18)
                .addComponent(jButtonPrintIngreList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonAddIngre)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditIngre)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeleteIngre)
                .addGap(18, 18, 18)
                .addComponent(jButtonViewIngre)
                .addGap(18, 18, 18)
                .addComponent(jButtonPrintIngre)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap(1186, Short.MAX_VALUE)
                    .addComponent(jLabel35)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel36)
                    .addGap(67, 67, 67)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel35))
                        .addComponent(jLabel36))
                    .addContainerGap(555, Short.MAX_VALUE)))
        );

        jTabbedPaneIngredient.addTab("Ingredients", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(1059, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPaneIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneIngredient)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-30.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-supplier-30.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-reception-30.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-shipped-30.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-gold-bars-30.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-graph-30.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-planner-30.png"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cookie-30.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void autoId()
        
     {
         try {
             Connection con;    
             con = DB.createsConnection();
             String sql="SELECT Ingrenumber FROM ingredientName";        
             PreparedStatement  ps=con.prepareStatement(sql);
             ResultSet rs=ps.executeQuery();
             rs.last(); // cursor will go to last row
             int row_count = rs.getRow(); // assign number of rows  to row_count variable
             String new_count = String.valueOf(row_count + 1); // increamet by 1
             int length = new_count.length(); // get new count length 
             String new_Ing_Number ="" ; // this is declare for assign new ing number
             
             if(length == 4 ){
                 new_Ing_Number = "ING" + new_count;
             }
             else if(length == 3 ){
                 new_Ing_Number = "ING0" + new_count;
             }
             else if(length == 2 ){
                 new_Ing_Number = "ING00" + new_count;
             }
             else if(length == 1 ){
                 new_Ing_Number = "ING000" + new_count;
             }
            jTextFieldIngreNumber5.setText(new_Ing_Number);
             
         } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }

    }
     
     public void FillCombo() 
     {
         jComboBoxName.removeAllItems();
          
         try{
          
             Connection con = null;    
             try {
                 con=DB.createsConnection();
             } catch (Exception ex) {
                 Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
             }
             String sql="SELECT Ingrename FROM ingredientname";
             PreparedStatement ps= con.prepareStatement(sql);
             ResultSet rs=ps.executeQuery();
             jComboBoxName.addItem("Select item");
             while (rs.next()){
                 jComboBoxName.addItem(rs.getString("Ingrename"));
             }
             }
         catch(SQLException ex)
                     {
                       JOptionPane.showMessageDialog(rootPane, ex);
                     }
         
         
     }
     
             
    
    
    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        FillCombo();
        autoId();
        jTextFieldIngName.setText("");
        jTextFieldIngDiscription.setText("");
           
            
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextFieldIngDiscriptionjTextFieldIngreNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngDiscriptionjTextFieldIngreNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngDiscriptionjTextFieldIngreNumberActionPerformed

    private void jButtonDeleteIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteIngreActionPerformed
        String sql="DELETE FROM `ingredientname` WHERE `Ingrenumber` = ?;";
        Connection con;
        PreparedStatement ps;
        try {
            con = DB.createsConnection();
            ps=con.prepareStatement(sql);
            
            String number=jTextFieldIngreNumber.getText();
            ps.setString(1, number);
        
            int i=ps.executeUpdate();
            if (i>0){
                JOptionPane.showMessageDialog(null, "Data is Deleted");
            }
            else{
                JOptionPane.showMessageDialog(null, "Data is not Deleted");   
            }  
            FillCombo();
            autoId();
            jTextFieldIngName.setText("");
            jTextFieldIngDiscription.setText(""); 
           
        } catch (Exception ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
 
             
    }//GEN-LAST:event_jButtonDeleteIngreActionPerformed

    private void jButtonEditIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditIngreActionPerformed
   
       
        String sql="UPDATE `ingredientname` SET `Ingrename` = ?, `discription` = ? WHERE `ingredientname`.`Ingrenumber` = ?;";
        Connection con;
        PreparedStatement ps;
        try {
            con = DB.createsConnection();
            ps=con.prepareStatement(sql);
            
            String name=jTextFieldIngName.getText();
            String dis=jTextFieldIngDiscription.getText();
            String number=jTextFieldIngreNumber.getText();
            ps.setString(1,name );
            ps.setString(2, dis);
            ps.setString(3, number);
                
               
             
            int i=ps.executeUpdate();
            if (i>0){
                JOptionPane.showMessageDialog(null, "Data is updated");
            }
            else{
                JOptionPane.showMessageDialog(null, "Data is not updated");   
            }  
            FillCombo();
            autoId();
            jTextFieldIngName.setText("");
            jTextFieldIngDiscription.setText(""); 
            
           
        } catch (Exception ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
 
                                              
    }//GEN-LAST:event_jButtonEditIngreActionPerformed

    private void jButtonReset2jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReset2jButtonResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReset2jButtonResetActionPerformed

    private void jTextFieldIngreNumber5jTextFieldIngreNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngreNumber5jTextFieldIngreNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngreNumber5jTextFieldIngreNumberActionPerformed

    private void jTextFieldIngreNumber7jTextFieldIngreNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngreNumber7jTextFieldIngreNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngreNumber7jTextFieldIngreNumberActionPerformed

    private void jButtonEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditProductActionPerformed

    private void jButtonDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteProductActionPerformed

    private void jTextFieldIngreNumber8jTextFieldIngreNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngreNumber8jTextFieldIngreNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngreNumber8jTextFieldIngreNumberActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonAddIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddIngreActionPerformed
        String Ingre_number= jTextFieldIngreNumber.getText();
        String Ing_name = jTextFieldIngName.getText();
        String discription= jTextFieldIngDiscription.getText();
        Connection con;
        String AddIngrename="INSERT INTO ingredientName(Ingrenumber,ingrename,discription) VALUES (?,?,?)";
        
        try {
                    con = DB.createsConnection();
                    PreparedStatement st =con.prepareStatement(AddIngrename);

                    st.setString(1, Ingre_number);
                    st.setString(2, Ing_name);
                    st.setString(3, discription);
                    

              int i=st.executeUpdate();
              if (i>0){
                  JOptionPane.showMessageDialog(null, "Data is saved");
              }
                  else{
                       JOptionPane.showMessageDialog(null, "Data is not saved");   
                          }
              
              FillCombo();
              autoId();
              jTextFieldIngName.setText("");
              jTextFieldIngDiscription.setText("");
                }
        
                catch (Exception ex) { 
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        } 
                
                                               
    }//GEN-LAST:event_jButtonAddIngreActionPerformed

    private void jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddProductActionPerformed

    private void jTextFieldIngNamejTextFieldIngreNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngNamejTextFieldIngreNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngNamejTextFieldIngreNumberActionPerformed

    private void jTextFieldIngreNumberjTextFieldIngreNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngreNumberjTextFieldIngreNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngreNumberjTextFieldIngreNumberActionPerformed

    private void jComboBoxNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxNamePopupMenuWillBecomeInvisible
        String gtdata=(String) jComboBoxName.getSelectedItem();
        String sql="SELECT * FROM ingredientname where Ingrename=?";
        Connection con;
        PreparedStatement ps;
        try {
            con = DB.createsConnection();
            ps=con.prepareStatement(sql);
            ps.setString(1,gtdata);
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("Ingrenumber");
                jTextFieldIngreNumber.setText(add1);
                 String add2=rs.getString("Ingrename");
                jTextFieldIngName.setText(add2);
                 String add3=rs.getString("discription");
                jTextFieldIngDiscription.setText(add3);
            }
            else
            {
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageProducts.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_jComboBoxNamePopupMenuWillBecomeInvisible

    private void jComboBoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNameActionPerformed

    private void jButtonIngreSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngreSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIngreSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);
              }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddIngre;
    private javax.swing.JButton jButtonAddProduct;
    private javax.swing.JButton jButtonDeleteIngre;
    private javax.swing.JButton jButtonDeleteProduct;
    private javax.swing.JButton jButtonEditIngre;
    private javax.swing.JButton jButtonEditProduct;
    private javax.swing.JButton jButtonIngreSearch;
    private javax.swing.JButton jButtonPrintIngre;
    private javax.swing.JButton jButtonPrintIngreList;
    private javax.swing.JButton jButtonPrintProduct;
    private javax.swing.JButton jButtonPrintProductPriceList;
    private javax.swing.JButton jButtonProductSearch;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonReset2;
    private javax.swing.JButton jButtonViewIngre;
    private javax.swing.JButton jButtonViewIngreList;
    private javax.swing.JButton jButtonViewProduct;
    private javax.swing.JButton jButtonViewProductPriceList;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPaneIngredient;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldIngDiscription;
    private javax.swing.JTextField jTextFieldIngName;
    private javax.swing.JTextField jTextFieldIngreNumber;
    private javax.swing.JTextField jTextFieldIngreNumber5;
    private javax.swing.JTextField jTextFieldIngreNumber7;
    private javax.swing.JTextField jTextFieldIngreNumber8;
    // End of variables declaration//GEN-END:variables

    private void autoID() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
